language: ruby
cache: bundler

notifications:
  email: false

before_install: gem install bundler -v '~> 1'

matrix:
  include:
    - rvm: 2.4.5
      gemfile: Gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/railsmaster.gemfile
  allow_failures:
    - rvm: 2.5.3
      gemfile: gemfiles/railsmaster.gemfile
