language: ruby
cache: bundler

notifications:
  email: false

matrix:
  include:
    - rvm: 2.4.3
      gemfile: Gemfile
    - rvm: 2.5.0
      gemfile: Gemfile
    - gemfile: gemfiles/rails5.gemfile
    - gemfile: gemfiles/railsmaster.gemfile
  allow_failures:
    - gemfile: gemfiles/railsmaster.gemfile
